# Generated by Django 5.2.11 on 2026-02-16 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaAnalitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('nombre_proyecto', models.CharField(max_length=200, verbose_name='Nombre de la solicitud')),
                ('descripcion', models.TextField()),
                ('tipo_solicitud', models.CharField(choices=[('DESEMBOLSO', 'Desembolso'), ('DESVIACION', 'Desviación')], max_length=20)),
                ('rubro_presupuestal', models.CharField(choices=[('SERVICIOS', 'Gastos de servicios y suministros'), ('ACTIVIDADES', 'Plan de actividades'), ('INVERSION', 'Inversión')], max_length=20)),
                ('presupuesto_pre_aprobado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_a_ejecutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('observaciones_supervisor', models.TextField(blank=True, null=True, verbose_name='Observaciones de Revisión')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cuenta_analitica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.cuentaanalitica')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.ubicacion')),
            ],
        ),
    ]
