# Generated by Django 5.2.11 on 2026-02-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
    ]
