# Generated by Django 5.2.11 on 2026-02-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_create_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudpresupuesto',
            old_name='nombre_proyecto',
            new_name='titulo',
        ),
    ]
