# Generated by Django 5.2.11 on 2026-02-19 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_rename_nombre_proyecto_solicitudpresupuesto_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('drive_id', models.CharField(max_length=255, unique=True)),
                ('url_view', models.TextField(verbose_name='Enlace de visualización')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo de archivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='presupuesto.solicitudpresupuesto')),
            ],
            options={
                'verbose_name': 'Adjunto de Solicitud',
                'verbose_name_plural': 'Adjuntos de Solicitudes',
                'db_table': 'AdjuntoSolicitud',
            },
        ),
    ]
