# Generated by Django 5.2.11 on 2026-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_adjuntosolicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Principal', max_length=100)),
                ('credentials_json', models.JSONField(help_text='Pega aquí el contenido completo del JSON de la Service Account')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
