# Generated by Django 5.2.11 on 2026-02-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0006_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='valor',
            field=models.CharField(max_length=100),
        ),
    ]
