# Generated by Django 5.2.11 on 2026-02-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0007_alter_configuracion_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntosolicitud',
            name='es_certificado',
            field=models.BooleanField(default=False, verbose_name='Es certificado'),
        ),
    ]
