# Generated by Django 5.2.11 on 2026-02-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0008_adjuntosolicitud_es_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(unique=True)),
                ('numero', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de Certificado',
                'verbose_name_plural': 'Secuencias de Certificados',
                'db_table': 'SecuenciaCertificado',
            },
        ),
    ]
