# Generated by Django 5.2.11 on 2026-02-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0009_secuenciacertificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntosolicitud',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado en certificado'),
        ),
    ]
