# Generated by Django 5.2.11 on 2026-02-24 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0010_adjuntosolicitud_aprobado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('SSD', 'Santo Domingo'), ('STI', 'Santiago'), ('NAG', 'Nagua')], max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.sede'),
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
