# Generated by Django 5.2.11 on 2026-02-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0011_sede_alter_solicitudpresupuesto_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
