# Generated by Django 5.2.11 on 2026-02-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0012_alter_sede_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
    ]
