from django.db import migrations

def cargar_cuentas_analiticas(apps, schema_editor):
    CuentaAnalitica = apps.get_model('presupuesto', 'CuentaAnalitica')
    
    datos = [
        ("CA-0163", "JUNTA DE DIRECTORES"), ("CA-0164", "RECTORIA"), ("CA-0165", "CASA SAMANA"),
        ("CA-0167", "DEPARTAMENTO DE ASUNTOS RECTORALES"), ("CA-0170", "DEPARTAMENTO LEGAL"),
        ("CA-0171", "SECRETARIA GENERAL"), ("CA-0173", "DEPARTAMENTO DE REGISTRO"),
        ("CA-0174", "UNIDAD DE REGISTRO SANTO DOMINGO"), ("CA-0175", "UNIDAD DE REGISTRO CIBAO ORIENTAL"),
        ("CA-0176", "VICERRECTORIA DE PLANIFICACION, INNOVACION Y DESARROLLO"),
        ("CA-0177", "DIRECCIÓN DE ASEGURAMIENTO DE LA CALIDAD"), ("CA-0181", "VICERRECTORÍA ACADÉMICA"),
        ("CA-0182", "ESCUELA DE CIENCIAS JURÍDICAS Y POLÍTICAS SANTIAGO"),
        ("CA-0183", "ESCUELA DE EDUCACIÓN Y FORMACIÓN GENERAL SANTIAGO"),
        ("CA-0184", "ESCUELA DE NEGOCIOS Y TURISMO SANTIAGO"), ("CA-0185", "ESCUELA DE INGENIERÍA Y TECNOLOGÍA SANTIAGO"),
        ("CA-0186", "COORDINACIÓN DE AGRIMENSURA SANTIAGO"), ("CA-0187", "ESCUELA DE CIENCIAS DE LA SALUD Y PSICOLOGÍA SANTIAGO"),
        ("CA-0189", "ESCUELA DE CIENCIAS SOCIALES Y COMUNICACIÓN SANTIAGO"), ("CA-0191", "DEPARTAMENTO DE IDIOMAS SANTIAGO"),
        ("CA-0192", "DEPARTAMENTO DE EVALUACIÓN DE LOS APRENDIZAJES SANTIAGO"), ("CA-0194", "DEPARTAMENTO DE CURSO FINAL DE GRADO SANTIAGO"),
        ("CA-0195", "DEPARTAMENTO DE PRÁCTICA PROFESIONAL Y SERVICIO SOCIAL"),
        ("CA-0196", "DEPARTAMENTO DE SERVICIO AL PARTICIPANTE Y VIDA UNIVERSITARIA"),
        ("CA-0197", "DEPARTAMENTO DE GESTIÓN Y DESARROLLO CURRICULAR SANTIAGO"), ("CA-0198", "CINGEP"),
        ("CA-0202", "COORDINACIÓN ACADÉMICA EUROPA"), ("CA-0203", "COORDINACIÓN ACADÉMICA ESTADOS UNIDOS"),
        ("CA-0204", "DIRECCION ACADEMICA SANTO DOMINGO"), ("CA-0205", "ESCUELA DE CIENCIAS JURÍDICAS Y POLÍTICAS SANTO DOMINGO"),
        ("CA-0206", "ESCUELA DE EDUCACIÓN Y FORMACIÓN GENERAL SANTO DOMINGO"), ("CA-0207", "ESCUELA DE NEGOCIOS Y TURISMO SANTO DOMINGO"),
        ("CA-0208", "ESCUELA DE INGENIERÍA Y TECNOLOGÍA SANTO DOMINGO"), ("CA-0209", "ESCUELA DE CIENCIAS DE LA SALUD Y PSICOLOGÍA SANTO DOMINGO"),
        ("CA-0213", "DEPARTAMENTO DE IDIOMAS SANTO DOMINGO"), ("CA-0214", "DEPARTAMENTO DE EVALUACIÓN DE LOS APRENDIZAJES SANTO DOMINGO"),
        ("CA-0216", "DEPARTAMENTO DE CURSO FINAL DE GRADO SANTO DOMINGO"), ("CA-0217", "DEPARTAMENTO DE PRÁCTICA PROFESIONAL Y SERVICIO SOCIAL SANTO DOMINGO"),
        ("CA-0218", "DEPARTAMENTO DE SERVICIO AL PARTICIPANTE Y VIDA UNIVERSITARIA SANTO DOMINGO"),
        ("CA-0221", "DIRECCION ACADEMICA CIBAO ORIENTAL"), ("CA-0222", "ESCUELA DE CIENCIAS JURÍDICAS Y POLÍTICAS CIBAO ORIENTAL"),
        ("CA-0223", "ESCUELA DE EDUCACIÓN Y FORMACIÓN GENERAL CIBAO ORIENTAL"), ("CA-0224", "ESCUELA DE NEGOCIOS Y TURISMO CIBAO ORIENTAL"),
        ("CA-0225", "ESCUELA DE INGENIERÍA Y TECNOLOGÍA CIBAO ORIENTAL"), ("CA-0226", "ESCUELA DE CIENCIAS DE LA SALUD Y PSICOLOGIA CIBAO ORIENTAL"),
        ("CA-0230", "DEPARTAMENTO DE EVALUACIÓN DE LOS APRENDIZAJES CIBAO ORIENTAL"), ("CA-0232", "DEPARTAMENTO DE CURSO FINAL DE GRADO CIBAO ORIENTAL"),
        ("CA-0233", "DEPARTAMENTO DE PRÁCTICA PROFESIONAL Y SERVICIO SOCIAL CIBAO ORIENTAL"),
        ("CA-0234", "DEPARTAMENTO DE SERVICIO AL PARTICIPANTE Y VIDA UNIVERSITARIA CIBAO ORIENTAL"),
        ("CA-0236", "CINGEP CIBAO ORIENTAL"), ("CA-0237", "VICERRECTORÍA DE INVESTIGACIÓN Y POSGRADO"),
        ("CA-0238", "DIRECCION ACADÉMICA DE POSGRADO, SEDE"), ("CA-0240", "DEPARTAMENTO DE INVESTIGACIÓN Y DIVULGACIÓN CIENTÍFICA"),
        ("CA-0241", "PROFUNDO"), ("CA-0242", "DOCTORADO"), ("CA-0243", "DIRECCION ACADÉMICA DE POSGRADO, SANTO DOMINGO"),
        ("CA-0246", "DIRECCION ACADÉMICA DE POSGRADO, CIBAO ORIENTAL"), ("CA-0247", "VICERRECTORÍA ADMINISTRATIVA Y FINANCIERA"),
        ("CA-0248", "DIRECCION ADMINISTRATIVA SANTIAGO"), ("CA-0250", "UNIDAD DE CONSERJERIA SANTIAGO"),
        ("CA-0251", "UNIDAD DE MANTENIMIENTO SANTIAGO"), ("CA-0252", "UNIDAD DE TRANSPORTACIÓN SANTIAGO"),
        ("CA-0253", "UNIDAD DE SEGURIDAD FÍSICA SANTIAGO"), ("CA-0254", "UNIDAD DE SEGURIDAD Y SALUD LABORAL SANTIAGO"),
        ("CA-0255", "UNIDAD DE ALMACÉN SANTIAGO"), ("CA-0257", "DIRECCION ADMINISTRATIVA SANTO DOMINGO"),
        ("CA-0259", "UNIDAD DE CONSERJERÍA SANTO DOMINGO"), ("CA-0260", "UNIDAD DE MANTENIMIENTO SANTO DOMINGO"),
        ("CA-0261", "UNIDAD DE TRANSPORTACIÓN SANTO DOMINGO"), ("CA-0262", "UNIDAD DE GESTIÓN DEL TALENTO HUMANO SANTO DOMINGO"),
        ("CA-0263", "UNIDAD DE SEGURIDAD FÍSICA SANTO DOMINGO"), ("CA-0264", "UNIDAD DE ALMACÉN SANTO DOMINGO"),
        ("CA-0266", "UNIDAD DE ADMISIONES SANTO DOMINGO"), ("CA-0267", "UNIDAD DE BIBLIOTECA SANTO DOMINGO"),
        ("CA-0268", "ECONOUAPA SANTO DOMINGO"), ("CA-0269", "DIRECCION ADMINISTRATIVA CIBAO ORIENTAL"),
        ("CA-0272", "UNIDAD DE CONSERJERÍA CIBAO ORIENTAL"), ("CA-0273", "UNIDAD DE MANTENIMIENTO CIBAO ORIENTAL"),
        ("CA-0274", "UNIDAD DE TRANSPORTACIÓN CIBAO ORIENTAL"), ("CA-0275", "UNIDAD DE GESTIÓN DEL TALENTO HUMANO CIBAO ORIENTAL"),
        ("CA-0276", "UNIDAD DE ALMACÉN CIBAO ORIENTAL"), ("CA-0277", "UNIDAD DE SEGURIDAD FÍSICA CIBAO ORIENTAL"),
        ("CA-0279", "UNIDAD DE ADMISIONES CIBAO ORIENTAL"), ("CA-0280", "UNIDAD DE BIBLIOTECA CIBAO ORIENTAL"),
        ("CA-0281", "ECONOUAPA CIBAO ORIENTAL"), ("CA-0282", "ECONOUAPA SANTIAGO"),
        ("CA-0283", "DEPARTAMENTO DE GESTIÓN DEL TALENTO HUMANO"), ("CA-0284", "DEPARTAMENTO DE ADMISIONES"),
        ("CA-0285", "DEPARTAMENTO DE COMUNICACIÓN CORPORATIVA"), ("CA-0287", "UNIDAD DE EGRESADOS"),
        ("CA-0289", "UNIDAD DE RELACIONES PUBLICAS"), ("CA-0290", "DEPARTAMENTO DE CAPTACION"),
        ("CA-0293", "DEPARTAMENTO DE PUBLICACIONES"), ("CA-0295", "DEPARTAMENTO DE BIBLIOTECA"),
        ("CA-0296", "CENTRO DE CAPACITACIÓN PROFESIONAL (CAP)"), ("CA-0297", "CENTRO DE CAPACITACIÓN PROFESIONAL (CAP) SANTO DOMINGO"),
        ("CA-0298", "UNIDAD DE CAPACITACIÓN PROFESIONAL (CAP) CIBAO ORIENTAL"), ("CA-0299", "DIRECCION FINANCIERA"),
        ("CA-0300", "DEPARTAMENTO de CONTABILIDAD"), ("CA-0301", "UNIDAD DE CONTABILIDAD SANTO DOMINGO"),
        ("CA-0302", "UNIDAD DE CONTABILIDAD CIBAO ORIENTAL"), ("CA-0303", "DEPARTAMENTO DE TESORERIA"),
        ("CA-0304", "UNIDAD DE TESORERÍA SANTO DOMINGO"), ("CA-0305", "UNIDAD DE TESORERÍA CIBAO ORIENTAL"),
        ("CA-0306", "DEPARTAMENTO DE COMPRAS"), ("CA-0307", "UNIDAD DE CREDITO Y BECAS"),
        ("CA-0308", "UNIDAD DE PRESUPUESTO Y CONTROL DE GESTIÓN"), ("CA-0309", "VICERRECTORÍA DE COMUNICACIÓN Y VINCULACIÓN"),
        ("CA-0310", "DEPARTAMENTO DE VINCULACIÓN Y EXTENSIÓN"), ("CA-0324", "DEPARTAMENTO DE INNOVACIÓN"),
        ("CA-0326", "CENTRO UNIVERSITARIO DE EMPRENDIMIENTO (CUDE)"), ("CA-0327", "VICERRECTORÍA DE TECNOLOGÍA"),
        ("CA-0328", "DEPARTAMENTO DE DESARROLLO Y APLICACIONES"), ("CA-0334", "OFICINA DE APOYO HIGUEY"),
        ("CA-0335", "CENTRO DE ASESORÍA E INVESTIGACIÓN EDUCATIVA Y PSICOLÓGICA"),
        ("CA-0336", "CENTRO DE ASESORÍA Y DESARROLLO DE LA GESTIÓN UNIVERSITARIA"), ("CA-0338", "UNIDAD DE PROTOCOLO Y EVENTOS"),
        ("CA-0339", "DIRECCION ACADEMICA SANTIAGO"), ("CA-0340", "UNIDAD DE DISEÑO GRÁFICO Y AUDIOVISUAL"),
        ("CA-0342", "DEPARTAMENTO INFRAESTRUCTURA Y OPERACIONES"), ("CA-0344", "COORDINACIÓN DE ENFERMERÍA SANTIAGO"),
        ("CA-0346", "COORDINACIÓN DE ENFERMERÍA CIBAO ORIENTAL"), ("CA-0353", "UNIDAD DE CONTINUIDAD DE SERVICIOS TECNOLÓGICOS"),
        ("CA-0360", "DEPARTAMENTO DE PLANIFICACION"), ("CA-0367", "DEPARTAMENTO DE AUDITORIA Y CONTROL INTERNO"),
        ("CA-0390", "DEPARTAMENTO DE EXTENSION Y VOLUNTARIADO"), ("CA-0393", "FUPUAPA"),
        ("CA-0394", "ECONOENFERMERIA"), ("CA-0397", "CADESOFT"), ("CA-0696", "UNIDAD DE PLANEACION Y DISEÑO DE ESPACIOS"),
        ("CA-0550", "OFICINA DE APOYO SOSÚA"), ("CP-0349", "OFICINA DE APOYO NEIBA"),
        ("CP-0350", "OFICINA DE APOYO SAN JUAN"), ("CP-1130", "30º ANIVERSARIO"),
        ("CEGES-Santiago", "Santiago"), ("CEGES-SD", "Santo Domingo"),
        ("CEGES-A", "Las américas"), ("CEGES-NAG", "Nagua")
    ]

    for codigo, nombre in datos:
        CuentaAnalitica.objects.get_or_create(codigo=codigo, defaults={'nombre': nombre})

class Migration(migrations.Migration):
    dependencies = [
        ('presupuesto', '0015_cargar_cuentas_contables'), # Asegúrate de que apunte a tu última migración
    ]
    operations = [
        migrations.RunPython(cargar_cuentas_analiticas),
    ]