# Generated by Django 5.2.11 on 2026-03-07 09:35

from django.db import migrations

def cargar_sedes_iniciales(apps, schema_editor):
    # Obtenemos el modelo Sede a través del historial de la app
    Sede = apps.get_model('presupuesto', 'Sede')
    
    sedes = [
        {"codigo": "RCO", "nombre": "Nagua"},
        {"codigo": "RSD", "nombre": "Santo Domingo"},
        {"codigo": "RSS", "nombre": "Santiago de los Caballeros"},
    ]

    for sede_data in sedes:
        # update_or_create evita errores si ya existen los registros
        Sede.objects.update_or_create(
            codigo=sede_data["codigo"],
            defaults={"nombre": sede_data["nombre"]}
        )

class Migration(migrations.Migration):

    dependencies = [
        # Asegúrate de que apunte a la migración donde creaste el modelo Sede
        ('presupuesto', '0018_poblar_configuracion'), 
    ]

    operations = [
        migrations.RunPython(cargar_sedes_iniciales),
    ]