# Generated by Django 5.2.11 on 2026-03-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0020_alter_solicitudpresupuesto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpresupuesto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('POR_REVISION', 'Por Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15),
        ),
    ]
