# Generated by Django 5.2.11 on 2026-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0021_alter_solicitudpresupuesto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
