# Generated by Django 5.2.11 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0022_solicitudpresupuesto_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariosolicitud',
            name='estado',
            field=models.CharField(
                choices=[('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta')],
                default='PENDIENTE',
                max_length=20
            ),
        ),
    ]
