# Generated by Django 5.2.11 on 2026-04-07 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0025_create_compra_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpresupuesto',
            name='fecha_actividad',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
